### ISSUE TITLE
Cannot find hist folder

### ISSUE THREAD

**Issue by prateekdaniels** [letianzj/QuantResearch#1]
Hi Letianzj,

  You have an awesome collection of codes. I was unable to find the 'hist' folder which should consist the 'EWC US Equity.csv' and 'EWA US Equity.csv' files for the 'pairs_trading_kalman_filter.py' to run. I did try substituting it with prices from Yahoo and happen to get the below error:

numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

By any chance would you be able to upload the original 'hist' folder with the csv files ?

Thanks in advance

**Comment by letianzj** [comment]
Hi prateekdaniels,

I was actually also using the Yahoo data. I rerun the code and didn't get any error. 

for example, below I downloaded directly from yahoo,

#!pip install yfinance
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

sym_a = 'EWA'
sym_b = 'EWC'
start_date = datetime(2010, 1, 1)
end_date = datetime(2019, 12, 31)

data = yf.download([sym_a, sym_b], start_date, end_date)['Adj Close']

from pykalman import KalmanFilter

state_cov_multiplier = np.power(0.01, 2)       # 0.1: spread_std=2.2, cov=16  ==> 0.01: 0.22, 0.16
observation_cov = 0.001
# observation matrix F is 2-dimensional, containing sym_a price and 1
# there are data.shape[0] observations
obs_mat_F = np.transpose(np.vstack([data[sym_a].values, np.ones(data.shape[0])])).reshape(-1, 1, 2)

kf = KalmanFilter(n_dim_obs=1,                                      # y is 1-dimensional
                  n_dim_state=2,                                    #  states (alpha, beta) is 2-dimensinal
                  initial_state_mean=np.ones(2),                    #  initial value of intercept and slope theta0|0
                  initial_state_covariance=np.ones((2, 2)),         # initial cov matrix between intercept and slope P0|0
                  transition_matrices=np.eye(2),                    # G, constant
                  observation_matrices=obs_mat_F,                   # F, depends on x
                  observation_covariance=observation_cov,                   # v_t, constant
                  transition_covariance= np.eye(2)*state_cov_multiplier)           # w_t, constant

state_means, state_covs = kf.filter(data[sym_b])                 # observes sym_b price
beta_kf = pd.DataFrame({'Slope': state_means[:, 0], 'Intercept': state_means[:, 1]}, index=data.index)
beta_kf.plot(subplots=True)
plt.show()

**Comment by letianzj** [comment]
I'll close this ticket for now. Let me know if you run into anything.
