### ISSUE TITLE
PTO bars for each day?

### ISSUE THREAD

**Issue by rob3210** [letianzj/QuantResearch#8]
Appreciate your contributions here. For me, the main benefit of Market Profile is that it provides a quick and highly visual way of looking at several days’ worth of intraday price action. When looking at market profile across multiple days, instead of aggregating all of the PTO bars on the x-axis, would it be possible to show them above each date? This would involve removing the candlesticks and volume bars and just showing PTO arranged above each day. there are some indicative pictures here - https://www.epsilontheory.com/bitcoin-market-profile/

**Comment by letianzj** [comment]
Hi, afaik plotly does not have it off the shelf but it can always be customized. An alternative is to make subplots from left to right with a shared price axis.
